# Sample YAML file

input_menus:
  - C:\Users\retr0\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
  - C:\ProgramData\Microsoft\Windows\Start Menu\Programs

output_menu: C:\Users\retr0\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

misc_folder: "More/Apps"

temp_folder: "./start_menu_temp"

exclude_patterns:
  - "*uninstall*"
  - "*documentation*"
  - "*readme*"
  - "*help*"
  - "*.html"
  - "*.chm"
  - "*.pdf"
  - "*.url"

folders:
  Communicate:
    - Discord
    - Slack
    - Telegram
  Development:
    - Android Studio
    - Cursor
    - DB Browser (SQLite)
    - Docker Desktop
    - Genymotion
    - Git Bash
    - GitHub Desktop
    - Godot*
    - MongoDBCompass
    - Oracle VirtualBox
    - Postman
    - Unity*
    - Visual Studio*
    - Void
    - Windsurf
    - Yaak
  Gaming - Stores:
    - Battle.net
    - EA
    - Epic Games Launcher
    - GOG Galaxy
    - Steam
    - Ubisoft Connect
  Gaming - Tools:
    - NBTExplorer
  Gaming - Extra:
    - ES-DE
    - PPSSPP
    - Prism Launcher
    - RetroArch
    - Roblox Player
    - Roblox Studio
    - Sunshine
  Machine Learning:
    - a1111
    - AnythingLLM
    - Claude
    - ComfyUI
    - F5-TTS
    - fluxgym
    - Fooocus
    - GPT Researcher
    - Invoke Community Edition
    - Jan
    - kohya_ss
    - LM Studio
    - Local Deep Research
    - Msty
    - Ollama
    - OneTrainer
    - Pinokio
    - Stable Diffusion - Web UI
    - Ultimate Vocal Remover
    - Upscayl
  Scripts:
    - _ Run Casual Scripts
    - Fix Image Formats
    - On Wake Script
    - Organize Start Menu
    - Regenerate Music Playlists
    - Timeout Shutdown
  System & Hardware:
    - 7+ Taskbar Tweaker
    - Autoruns64
    - Benchmark - Cinebench
    - Benchmark - CrystalDiskMark 8
    - Benchmark - FurMark2*
    - Benchmark - Superposition
    - Benchmark - Valley
    - CPU-Z
    - CrystalDisk*
    - EarTrumpet
    - Equalizer - Configuration Editor
    - Equalizer - Configurator
    - Galaxy Buds
    - GPU-Z
    - HWiNFO*
    - HWiNFO64
    - HWMonitor
    - Kingston SSD Manager*
    - Logitech G HUB
    - MiniBin
    - MiniTool Partition Wizard
    - NVIDIA
    - "Open-Shell Menu Settings"
    - OpenRGB
    - OpenVPN Connect
    - PowerToys (Preview)
    - Winaero Tweaker
    - WizTree
  Tools:
    - AIMP - AudioConverter
    - AIMP - TagEditor
    - Audacity
    - Blender*
    - By Click Downloader
    - FileZilla
    - FL Studio*
    - GIMP*
    - HxD
    - Krita*
    - OBS Studio*
    - OpenVPN Connect
    - Oracle VM VirtualBox
    - RustDesk
    - XMedia Recode*
  Windows Accessories:
    - Command Prompt
    - File Explorer
    - Internet Explorer
    - Microsoft Edge
    - Notepad
    - Paint
    - Remote Desktop Connection
    - Run
    - Snipping Tool
    - Task Manager
    - Windows PowerShell
  Windows Administrative Tools:
    - Administrative Tools
    - Autoruns
    - Component Services
    - Computer Management
    - Control Panel
    - Defragment and Optimize Drives
    - Defragment Disks
    - Device Manager
    - Disk Cleanup
    - Event Viewer
    - iSCSI Initiator
    - Local Security Policy
    - Performance Monitor
    - PowerToys (Preview)
    - Process Explorer
    - Registry Editor
    - Resource Monitor
    - Security Configuration Management
    - Services
    - System Configuration
    - System Information
    - Task Scheduler
    - Windows Defender Firewall with Advanced Security
    - Windows Memory Diagnostic
