# Sample YAML file

input_menus:
  - C:\Users\retr0\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
  - C:\ProgramData\Microsoft\Windows\Start Menu\Programs
  
output_menu: C:\Users\retr0\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

misc_folder: "_ More"

temp_folder: "./start_menu_temp"

temp_folder: "./start_menu_temp"

exclude_patterns:
  - "*uninstall*"
  - "*documentation*"
  - "*readme*"
  - "*help*"
  - "*.html"
  - "*.chm"
  - "*.pdf"
  - "*.url"

folders:
  Communicate:
    - Discord
    - Telegram
    - Slack
  Development:
    - Git Bash
    - GitHub Desktop
    - Godot*
    - Postman
    - Visual Studio
    - Android Studio
    - Visual Studio Code
    - Visual Studio Code - Insiders
    - Oracle VirtualBox
    - Visual Studio Installer
    - Genymotion
    - Postman
    - DB Browser (SQLite)
    - Docker Desktop
    - Void
    - Yaak
    - Windsurf
    - Cursor
    - MongoDBCompass
    - Oracle VirtualBox
  Gaming - Stores:
    - EA
    - GOG Galaxy
    - Ubisoft Connect
    - Battle.net
    - Steam
    - Epic Games Launcher
  Gaming - Tools:
    - NBTExplorer
  Gaming - Extra:
    - Sunshine
    - Prism Launcher
    - Roblox Player
    - Roblox Studio
    - ES-DE
    - RetroArch
    - PPSSPP
  Machine Learning:
    - Stable Diffusion - Web UI
    - Fooocus
    - ComfyUI
    - Ultimate Vocal Remover
    - Upscayl
    - LM Studio
    - fluxgym
    - Ollama
    - a1111
    - kohya_ss
    - F5-TTS
    - Pinokio
    - Claude
    - Local Deep Research
    - GPT Researcher
    - OneTrainer
    - AnythingLLM
    - Msty
    - Jan
    - Invoke Community Edition
  Scripts:
    - _ Run Casual Scripts
    - Fix Image Formats
    - Regenerate Music Playlists
    - Organize Start Menu
    - On Wake Script
    - Timeout Shutdown
  System & Hardware:
    - Autoruns64
    - CPU-Z
    - GPU-Z
    - HWiNFO64
    - HWMonitor
    - WizTree
    - EarTrumpet
    - Galaxy Buds
    - OpenRGB
    - Benchmark - CrystalDiskMark 8
    - Benchmark - FurMark2*
    - Benchmark - Superposition
    - Benchmark - Valley
    - Benchmark - Cinebench
    - Logitech G HUB
    - Equalizer - Configurator
    - Equalizer - Configuration Editor
    - 7+ Taskbar Tweaker
    - MiniBin
    - "Open-Shell Menu Settings"
    - NVIDIA
    - Kingston SSD Manager*
    - MiniTool Partition Wizard
    - PowerToys (Preview)
    - CrystalDiskInfo Shizuku Edition
    - CrystalDiskMark 9 Shizuku Edition
    - OpenVPN Connect
    - HWiNFO
  Tools:
    - AIMP - AudioConverter
    - AIMP - TagEditor
    - Blender*
    - FileZilla
    - GIMP*
    - Krita*
    - OBS Studio*
    - Oracle VM VirtualBox
    - RustDesk
    - XMedia Recode*
    - HxD
    - OpenVPN Connect
    - Audacity
    - By Click Downloader
    - FL Studio*
  Windows Accessories:
    - Windows PowerShell
    - Command Prompt
    - File Explorer
    - Notepad
    - Paint
    - Remote Desktop Connection
    - Run
    - Snipping Tool
    - Task Manager
    - Internet Explorer
    - Microsoft Edge
  Windows Administrative Tools:
    - Defragment Disks
    - Control Panel
    - Administrative Tools
    - Component Services
    - Computer Management
    - Defragment and Optimize Drives
    - Disk Cleanup
    - Event Viewer
    - iSCSI Initiator
    - Local Security Policy
    - Performance Monitor
    - PowerToys (Preview)
    - Registry Editor
    - Resource Monitor
    - Services
    - System Configuration
    - System Information
    - Task Scheduler
    - Windows Defender Firewall with Advanced Security
    - Windows Memory Diagnostic
    - Security Configuration Management
    - Autoruns
    - Process Explorer
    - Device Manager
